### ISSUE TITLE
How can I use this handler from Caddyfile config ?

### ISSUE THREAD

**Issue by etherwvlf** [git001/caddyv2-upload#1]
upload_index.htm is a classic simple Javascript POST uploader.

Example Caddyfile I am trying to run:
```
:8888 {
	root * /var/test

	file_server /var/test/* {
		browse /var/test/upload_index.htm
	}

	upload  {
		dest_dir /var/test/tmp_upload
		max_filesize 0
	}

	log {
		output file access.log
        }
}
```
No matter how I rewrite the upload block of the config my attempts to run caddy with it are futile -
It gives
```
Error during parsing: Wrong argument count or unexpected line ending after 'upload'
```
It must be something very simple I am overlooking. Thanks in advance.

**Comment by git001** [comment]
Well as I prefer to use json config I have not add the Caddyfile in a reliable way.
I will take a look how to handle the config in Caddyfile.

**Comment by etherwvlf** [comment]
Thank you, I prefer Caddyfile for its simplicity, especially for configuring simple static servers.
I am sure I am not the only one.
When Caddy 2 launched, the lack of upload handler made me stick to Caddy v1 for quite a long time as I didn't want to install any server side languages to handle just a simple upload feature.
Thank you for your contribution to this beautiful piece of software and for taking the time to help me and the community.

**Comment by git001** [comment]
@etherwvlf does the latest comit works to you?
I have also updated the docker image on docker hub

**Comment by etherwvlf** [comment]
Sorry, I couldn't respond earlier...
I've been testing it whole day, and I must say everything is fine and dandy :)
Thank you kindly, sir !

**Comment by etherwvlf** [comment]
In caddyv2-upload)/upload.go on line 71:
```
zap.String("msg", "no ResponseTemplate specified (response_template), using the defualt one"),
```
there is a typo - "defualt" should be "default"
you might wanna change that.
