### ISSUE TITLE
Expose UUID as a variable

### ISSUE THREAD

**Issue by muety** [git001/caddyv2-upload#14]
I'm using `create_uuid_dir: true` and would like to return the actual, effective URL path of the file as part of the response. However, `http.upload.filename` only yields the plain name itself, while `http.upload.directory` has the whole file system path included. 

It would be super helpful if there was a `http.upload.uuiddir` variable.

**Comment by git001** [comment]
That's a good Idea. I will add this request.

**Comment by muety** [comment]
Any news on this? Should be quite a small change, I think...

**Comment by muety** [comment]
Don't wanna be annoying, but are there any chances to get this in? Either through my PR or the way you prefer to do it? I'd really need this, but would rather refrain from starting to maintain my own fork of this.

**Comment by git001** [comment]
@muety is now pushed to the repo
