### ISSUE TITLE
Feature request - Adding optional parameter allowing to force uploads to use specific filename

### ISSUE THREAD

**Issue by karowski** [git001/caddyv2-upload#18]
Hello,

In our project we have the need to rename each uploaded file to a specific filename. In the provided patch, an optional parameter has been added to allow the specification of a fixed filename. If set, all uploaded files will be renamed to the specified filename.

This functionality may be useful to others as well.

Thanks

https://gist.github.com/karowski/77aaca7f139243dc11fc5ab358f3ef36

**Comment by git001** [comment]
Hi @karowski .

looks like a good Idea.
Please can you create a pull request.
Maybe you can add the feature to replace some variables like https://github.com/git001/caddyv2-upload/blob/main/upload.go#L99 and some other repl lines.

**Comment by karowski** [comment]
Thanks for the fast reply.

I have created a pull request. However, I did not fully understand your request regarding the replace.

**Comment by git001** [comment]
close with #19
